#!/usr/bin/env bash
# gc-chkr installer entry header.
# Generated by scripts/build.sh — do not edit dist artifacts directly.
# Source modules live under src/installer/.

set -Eeuo pipefail
set -o pipefail

readonly PACKAGE_NAME="gc-chkr"
readonly PACKAGE_VERSION="__PACKAGE_VERSION__"
readonly PACKAGE_ARCH="all"
readonly PACKAGE_MAINTAINER="__PACKAGE_MAINTAINER__"
readonly PACKAGE_HOMEPAGE="__PACKAGE_HOMEPAGE__"
readonly MAIN_BIN="/usr/bin/gc-chkr"
readonly SHORT_BIN="/usr/bin/gchk"
readonly SYSTEMD_DIR="/lib/systemd/system"

ACTION=""
YES="false"
FORCE="false"
KEEP_DEB="false"
NO_COLOR="${NO_COLOR:-}"
TMP_BUILD_DIR=""
LAST_STEP="init"
