#!/usr/bin/env bash
# gc-hc tool runtime
# Generated by scripts/build.sh — do not edit dist artifacts directly.
# Source modules live under src/tool/.

set -Eeuo pipefail
set -o pipefail

readonly APP="gc-hc"
readonly VERSION="__PACKAGE_VERSION__"
readonly SYSTEM_BIN="/usr/bin/gc-hc"
readonly SHORT_BIN="/usr/bin/gchc"

SELF_PATH="$(readlink -f "$0" 2>/dev/null || printf '%s' "$0")"
SELF_DIR="$(cd -- "$(dirname -- "$SELF_PATH")" >/dev/null 2>&1 && pwd -P)"

if [[ "$SELF_PATH" == "$SYSTEM_BIN" || "$SELF_PATH" == "$SHORT_BIN" ]]; then
  readonly MODE="system"
  readonly CONFIG_DIR="${GC_HC_CONFIG_DIR:-/etc/gc-hc}"
  readonly STATE_DIR="${GC_HC_STATE_DIR:-/var/lib/gc-hc}"
  readonly LOG_DIR="${GC_HC_LOG_DIR:-/var/log/gc-hc}"
else
  readonly MODE="standalone"
  readonly BASE_DIR="${GC_HC_HOME:-${SELF_DIR}/.gc-hc}"
  readonly CONFIG_DIR="${GC_HC_CONFIG_DIR:-${BASE_DIR}}"
  readonly STATE_DIR="${GC_HC_STATE_DIR:-${BASE_DIR}/state}"
  readonly LOG_DIR="${GC_HC_LOG_DIR:-${BASE_DIR}/log}"
fi

readonly CONFIG_FILE="${CONFIG_DIR}/env"
readonly RESULT_FILE="${STATE_DIR}/last.json"
readonly LOG_FILE="${LOG_DIR}/gc-hc.log"
readonly SERVICE_NAME="gc-hc.service"
readonly TIMER_NAME="gc-hc.timer"
readonly TIMER_OVERRIDE_DIR="/etc/systemd/system/gc-hc.timer.d"
readonly TIMER_OVERRIDE_FILE="${TIMER_OVERRIDE_DIR}/override.conf"

readonly ALLOY_ENV_FILES=(
  "/etc/default/alloy"
  "/etc/sysconfig/alloy"
)
